### ISSUE TITLE
Market multiplayer issue

### ISSUE THREAD

**Issue by Sorax5** [BetaZavr/CustomNPCs_1.12.2-Unofficial#2]
Hello, I am using your customNpc fork and I have a problem with the markets.

I have created a custom market so far so good, I put the NPC in Trader then I give him my market.

From that moment on I'm the only one who can open the market, the other players can't do it.

If I ever restart the server and I reconnect and I right click on my NPC who has my market it does not work again and I am forced to reedit the market that the trader has.
I've tried to compile the mod myself and add logs (with Logwriter) in the RoleTrader it finds the market in the MarcetController but it doesn't show me the custom market interface. I have the impression that it's more of a GUI problem that wouldn't be recorded.

I hope my explanations are clear if ever do not hesitate to ask me for more information.

Apart from this problem, your modifications to the basic mod are really cool!

**Comment by Sorax5** [comment]
I forgot to mention it but I'm using Mohist 1.12.2 but I tested with Magma 1.12.2 and I have the same problem.

**Comment by BetaZavr** [comment]
Now all merchants have been redesigned, as well as their shops
