### ISSUE TITLE
Modular Warfare - несовместимость

### ISSUE THREAD

**Issue by syndragon09** [BetaZavr/CustomNPCs_1.12.2-Unofficial#3]
[crash-2023-10-28_02.59.50-client.txt](https://github.com/BetaZavr/CustomNPCs_1.12.2-Unofficial/files/13193969/crash-2023-10-28_02.59.50-client.txt)

При игре с модом ModularWarfare крашится игра.

**Comment by BetaZavr** [comment]
Капа всех элементов мода исправлена
